### ISSUE TITLE
Realm not completing gather copy on the GPU

### ISSUE THREAD

**Issue by piyueh** [nv-legate/legate.numpy#11]
## Problem

Advanced indexing of a relatively huge (e.g., length 10K) 1D array returns `UnboundLocalError: local variable 'shardfn' referenced before assignment`, rather than `NotImplementedError`.

I understand that advanced indexing is mostly not yet implemented. Most related routines raise `NotImplementedError` to let users know about this situation. However, this particular use case raises this different error, which seems to be a bug to me.

## To reproduce

1. step 1: prepare `test.py`:
   ```python
   from legate import numpy
   a = numpy.arange(10000)
   print(a[(1, 2, 3), ]) 
   ```
2. step 2: run with, for example
   ```shell
   $ legate --cpus 1 test.py
   ```

## Output

```python
Traceback (most recent call last):
  File "<blahblah>/lib/python3.8/site-packages/legion_top.py", line 394, in legion_python_main
    run_path(args[start], run_name='__main__')
  File "<blahblah>/lib/python3.8/site-packages/legion_top.py", line 193, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "./test.py", line 3, in <module>
    print(a[(1, 2, 3), ])
  File "<blahblah>/lib/python3.8/site-packages/legate/numpy/array.py", line 381, in __getitem__
    shape=None, thunk=self._thunk.get_item(key, stacklevel=2)
  File "<blahblah>/lib/python3.8/site-packages/legate/numpy/deferred.py", line 414, in get_item
    copy = Copy(mapper=self.runtime.mapper_id, tag=shardfn)
UnboundLocalError: local variable 'shardfn' referenced before assignment
```

## Expected results

Either `[1, 2, 3]` or `NotImplementedError`.

## Notes

- Interestingly, smaller arrays do not have this issue. For example, if `a = numpy.arange(100)`, the code works fine.
- Another way to make it works is to use GPUs instead of CPUs. For example, `legate --gpus 1 test.py` works fine. This is interesting, as the GPU implementation seems to be more stable than CPU implementation?

**Comment by piyueh** [comment]
I added notes regarding using GPUs.

**Comment by lightsighter** [comment]
Fixed with `f227ed7431`. Was just a typo. You would need a bigger array to see the same effect on GPUs. Legate won't offload to accelerators unless it thinks that it will be a performance win.

**Comment by piyueh** [comment]
Hi, I was still not able to get the expected result when using flag `-lg:numpy:test` with GPU. Also, with CPU, I got the correct output but also got a warning from Legion. Here's my test code:

```python
from legate import numpy
a = numpy.arange(50000)
idx = numpy.random.randint(0, 10000, 5000, int)
print(a[idx, ])
print(a[[1, 2, 3], ])
```

1. Using CPU (`legate --cpus 1 ./test.py -lg:numpy:test`),  I got warnings and also the correct answer:
   ```
   [0 - 7f980aa7aa80]    0.790074 {4}{runtime}: [warning 1071] LEGION WARNING: Region requirement 1 of
   operation Copy (UID 7) in parent task legion_python_main (UID 1) is using uninitialized data for field(s)
   1048578 of logical region (2,1,2) (from file <prefix>/legate.core/legion/runtime/legion/legion_ops.cc:1192)
   For more information see:
   http://legion.stanford.edu/messages/warning_code.html#warning_code_1071
   
   [4250 3719 2489 ... 5808 6931 9231]
   [0 - 7f980aa7aa80]    0.821821 {4}{runtime}: [warning 1071] LEGION WARNING: Region requirement 1 of
   operation Copy (UID 12) in parent task legion_python_main (UID 1) is using uninitialized data for field(s)
   1048578 of logical region (3,1,3) (from file <prefix>/legate.core/legion/runtime/legion/legion_ops.cc:1192)
   For more information see:
   http://legion.stanford.edu/messages/warning_code.html#warning_code_1071

   [1 2 3]
   ```
2. Using GPU (`legate --gpus 1 ./test.py -lg:numpy:test`), I first got this warning:
   ```
   [0 - 7fa3536cfa80]    1.620641 {4}{runtime}: [warning 1071] LEGION WARNING: Region requirement 1 of
   operation Copy (UID 7) in parent task legion_python_main (UID 1) is using uninitialized data for field(s)
   1048578 of logical region (2,1,2) (from file <prefix>/legate.core/legion/runtime/legion/legion_ops.cc:1192)
   For more information see:
   http://legion.stanford.edu/messages/warning_code.html#warning_code_1071
   ```
   And then the program just hung. No more outputs, and it was not terminated either.

**Comment by lightsighter** [comment]
@piyueh You can safely ignore the warnings. We'll try to make them go away in the future by telling Legion the right privileges, but in this case they are not causing any issues.

@streichler The single GPU case is hanging because Realm is not completing a gather copy on the GPU. Please see the output below:

```
../LegateCore/install/bin/legate --gpus 1 ./test1.py -lg:numpy:test --fbmem 2048 -lg:inorder -level dma=1,copy=1

[0 - 7f3c3024f000]    1.646389 {2}{dma}: dma request 0x7f3a74004f10 created - plan=0x7f3a74004960 before=0 after=8000000000400011
[0 - 7f3c3024f000]    1.646398 {2}{dma}: dma request 0x7f3a74004f10 ready - plan=0x7f3a74004960 before=0 after=8000000000400011
[0 - 7f3c3024f000]    1.646522 {2}{dma}: dma request 0x7f3a74004f10 started - plan=0x7f3a74004960 before=0 after=8000000000400011
```

The copy was issued to Realm and didn't have any event precondition. Realm clearly started the DMA request, but it never finished.

**Comment by streichler** [comment]
@lightsighter @piyueh can I ask one of you to run with `-level dma=2,xplan=1` and paste the log messages?  This may be an instance of https://github.com/StanfordLegion/legion/issues/1070.

**Comment by streichler** [comment]
I think I have a fix for this in this commit: https://gitlab.com/StanfordLegion/legion/-/commit/d540961c32940e90854d731715a82db2b311a972

@manopapad can you help me test that it does indeed fix the hang here?

**Comment by lightsighter** [comment]
@streichler I've confirmed that the hang is gone. Let me know when you merge the branch so I can upstream it.

**Comment by manopapad** [comment]
It looks like the above commit is in control_replication but not legate_stable. @lightsighter do you want to merge it into legate_stable as well, then we can close this issue?

**Comment by manopapad** [comment]
This seems to be fixed
